### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by noctis90210** [anidl/crunchyroll-downloader-nx#6] opened 2020-05-29 20:38 UTC
> crunchy -s 21695 -e 353 --dlsubs enUS --mks -q max
> === Crunchyroll Downloader NX 4.17.0 ===
> [ERROR] HTTPError 403: Forbidden

I keep on getting this error 2 days ago when im going to download a file (video/sub) it always go to that error without any details, it just stop there.

**Comment by bgette** [comment] 2020-05-29 23:22
Duplicate of https://github.com/anidl/crunchyroll-downloader-nx/issues/5.

**Comment by noctis90210** [comment] 2020-05-30 07:07
issue #5 seems he can still download subtitles only... but now when i tried to download a subtitle file, it throws a 403 error.

**Closed** 2020-06-02 08:48 UTC
